"""empty message

Revision ID: 2e880a9cae39
Revises: 7b146e159510
Create Date: 2022-12-05 22:41:46.474165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e880a9cae39'
down_revision = '7b146e159510'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
