"""empty message

Revision ID: 32f6830495c0
Revises: 2e880a9cae39
Create Date: 2022-12-05 22:42:38.001035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f6830495c0'
down_revision = '2e880a9cae39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
