"""empty message

Revision ID: 6830a66a8cad
Revises: c482c91fd802
Create Date: 2022-11-20 20:02:03.431928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6830a66a8cad'
down_revision = 'c482c91fd802'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_posts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_posts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_posts', type_='foreignkey')
    op.drop_column('user_posts', 'user_id')
    # ### end Alembic commands ###
